<?php

namespace PF\AgendaBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function getRoleConseille($role)
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select('u')
			->from('PFAgendaBundle:User', 'u')
			->where($qb->expr()->orX(
				$qb->expr()->like('u.roles', ':roles')
			))
			->setParameter('roles', $role);

		return $qb->getQuery()->getResult();
	}
}
