<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVi1trxr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVi1trxr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVi1trxr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVi1trxr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVi1trxr\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vi1trxr',
    'container.build_id' => '5de37c30',
    'container.build_time' => 1527269024,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVi1trxr');
