<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPcukxjh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPcukxjh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPcukxjh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPcukxjh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPcukxjh\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pcukxjh',
    'container.build_id' => '1aad1c33',
    'container.build_time' => 1526303741,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPcukxjh');
