<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container27xhlvr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container27xhlvr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container27xhlvr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container27xhlvr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container27xhlvr\appDevDebugProjectContainer(array(
    'container.build_hash' => '27xhlvr',
    'container.build_id' => '1038d5d9',
    'container.build_time' => 1526820196,
), __DIR__.\DIRECTORY_SEPARATOR.'Container27xhlvr');
